### ISSUE TITLE
Do I need a developer account if I only plan to do semi-integrations to Clover Flex?

### ISSUE THREAD

**Issue by AlexZhouAA** [clover/remote-pay-cloud-examples#75]
I asked, someone told me I need a developer account to do the semi-integration, but I read all the code.
I can't find the reason why I need a developer account to do it.
Please advise.  Thanks so much

**Comment by dxcook5** [comment]
A developer account is required to perform many tasks with the Clover developer platform. For a semi-integration, one of the requirements is a [Remote Application ID (RAID)](https://docs.clover.com/docs/create-your-remote-app-id). This ID is generated on the developer dashboard which you access with your developer account.

If you are interested in building a semi-integration, please fill out the application on this page: https://docs.clover.com/docs/application.

**Comment by AlexZhouAA** [comment]
@dxcook5 Thank you so much. It's very helpful.
I searched everywhere, but I can't get the answer. Here's the question,
I do a semi-integration to connect Clover Flex to our existing POS system which is browser based.
We'll choose Javascript platform, therefore we don't need to develop an android app to be installed on the Clover Flex device.
Our POS system can connect to the Clover Flex device with the RAID which is generated from the developer dashboard.
Is that right? I really appreciate your help.

Thanks again.

**Comment by dxcook5** [comment]
@AlexZhouAA , you are correct.

- You can use the Remote Pay Cloud SDK to connect your browser-based POS to the Clover Flex.
- You will not need to develop your own Android app. Clover maintains two apps that handle the connection and interaction with the device, [Secure Network Pay Display](https://docs.clover.com/docs/pay-display-apps#secure-network-pay-display) and [Cloud Pay Display](https://docs.clover.com/docs/pay-display-apps#cloud-pay-display).
- You will pass the RAID as part of the connection configuration for your POS. See [this tutorial](https://docs.clover.com/docs/cloud-sdk-v3#configure-a-connection) for more information.

If you haven't already done so, please fill out the application linked in my previous message.
